apiVersion: apps/v1
kind: Deployment
metadata:
  name: homelab-demo
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: homelab-demo
  template:
    metadata:
      labels:
        app: homelab-demo
    spec:
      containers:
      - name: homelab-demo
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.containerPort }}
